import type { Metadata } from "next";
import "./globals.css";

import { fontVariables } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Eclipse 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-slate-100 ${fontVariables}`}>{children}</body>
    </html>
  );
}
