import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

import { Navigation } from "@/components/ui/navigation";
import { fontVariables } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Eclipse 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-slate-100 font-lexend ${fontVariables}`}>
        <main className="flex min-h-screen flex-col">
          <div className="w-full bg-black">
            {/* Hero container */}
            <div className="container relative h-[200px] max-w-screen-sm">
              <Image
                src="/img/eclipse-background.jpg"
                alt="Total Solar Eclipse image background"
                quality={100}
                fill
                sizes="100vw"
                style={{
                  objectFit: "contain",
                }}
              />
            </div>
          </div>
          <div className="min-h-[900px] w-full bg-zinc-400 bg-gradient-to-b from-black from-50% to-zinc-400">
            {/* Main content container */}
            <div className="container flex max-w-screen-lg flex-col gap-8">
              <div className="text-center">
                <h1 className="inline-block animate-text bg-gradient-to-r from-gray-200 to-gray-900 bg-clip-text font-bebas-neue text-8xl font-bold text-transparent">
                  <Link href="/">Eclipse Solar 2024</Link>
                </h1>
              </div>
              <div className="self-center">
                <Navigation />
              </div>
              <div className="mb-10 text-gray-200">{children}</div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
